# Generated by Django 3.1.1 on 2020-09-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=30, verbose_name='Название поста')),
                ('post', models.TextField(verbose_name='Пост')),
                ('author', models.CharField(max_length=30, verbose_name='Автор')),
                ('time_creation', models.DateTimeField(verbose_name='Время создания')),
                ('time_publication', models.DateTimeField(verbose_name='Время публикации')),
                ('time_update', models.DateTimeField(verbose_name='Время обновления')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
        ),
    ]
